name: Arduino_CI

on: [push, pull_request]

jobs:
  arduino_ci:
    name: "Arduino CI - OS(Ubuntu)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Arduino-CI/action@master
